### ISSUE TITLE
Watching subfolders with ejs-files?

### ISSUE THREAD

**Issue by rowild** [testerum/ejs-compiled-loader-webpack4-nodeps#2]
I ask here, because I do not know, where else! Please redirect me, if this is the wrong place - thank you!

I have subfolders with ejs-files, like this:

```
src
-- shared
-- startpage
-- subpage
---- shared
```

Unfortunately, webpack does not recognize, when there are changes.
From my webpack config:

```
module: {
  rules: [
      // HTML/EJS
      {
        test: /\.ejs$/,
        exclude: /(node_modules)/,
        use: [{
          loader: '@testerum/ejs-compiled-loader-webpack4-nodeps',
          options: {
            ejsOptions: {
              compileDebug: true
            },
            data: {
              title: 'New Title',
              someVar: 'hello world'
            },
            htmlmin: false,
            htmlminOptions: {
              removeComments: true
            }
          }
        }]
      },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.ejs",
      filename: "index.html",
      title: "Some Title",
      minify: {
        removeComments: true,
        collapseWhitespace: true
      }
    }),
```

What am I doing wrong? Do you happen to have any advice for me?
Thank you!

**Comment by cvmocanu** [comment]
From your configuration, I see a misunderstanding. The ``data`` (at path ``module.rules[0].use[0].options.data``) tells me you misunderstand this plugin.
Let me explain.

There are at lease 2 types of EJS webpack plugins out there:
1. The ones that hard-code the model in the webpack configuration file, like you have done. These plugins will render the template at **build time**. So when you use it so: ``const renderedData = require("./template.ejs");``, and you get back the rendered template.
2. The ones that only compile the template at build time, and you have to provide the model **at run time** to render the template. This is how ``@testerum/ejs-compiled-loader-webpack4-nodeps`` works, so this plugin doesn't need the ``data`` model at build-time. Only compiling the templates (as opposed to rendering them) is the more flexible approach, since you will seldom be able to hard-code the model at build-time.

I've updated the README.md with this info and and also added a demo at [@testerum/ejs-compiled-loader-webpack4-nodeps-ts-demo](https://github.com/testerum/ejs-compiled-loader-webpack4-nodeps-ts-demo).

As for webpack not detecting changes, if you do ``npm run watch`` in the demo project, webpack detects changes both in normal source code (``main.ts``) and also in the template (``templates/hello.ejs``).

**Comment by rowild** [comment]
Thanks for your feedback! Actually, I am not using the data attr, sorry for the confusion! (I guess it is a remainder of a configuration for another ejs plugin...?)

I do appreciate your explanations - but will need time to consume them! If I fail, I will try to get in touch with you again. But be assured, that I highly appreciate you pointing me in the proper direction!

As for the compilation: I have files at the root level (src), which are recognized just fine, when changes are made. But those ejs-files in the subfolders seem to not receive a watcher... I was wondering, if you knew, why? (This is probably not plugin-related, but a general error in my webpack config?)

**Comment by rowild** [comment]
Hi, Cristian, i think you should keep this issue open, because it really seems to a bug. Here is how to replicate:

Example setup:

- index.ejs
-- src/header.ejs
-- src/shared/logo.ejs

`index.ejs` includes header, and `header.ejs` includes `logo.ejs`. 

Whenever code is changed in `index.ejs` or even `header.ejs`, webpack recognized that, reloads and implements the changes.
On the other hand: When code is changed in `logo.ejs`, webpack does NOT reload and will therefore show the changes; a webpack restart is necessary for a fresh recompile. Also, if at the same time, there is a change is, e.g., a scss file, webpack does reload, but it still does not recognize the changes in logo.ejs.

According to some sources on SO, it seems other ejs loader acted the same way. Maybe this is not a problem of webpack?
(Or maybe I am really so incredibly blind that I just cannot find the error in my setup... but since everything else is working fine, I doubt that. Even the HTMLloader loads deeply nested files, if I do not use ejs...)

I will report again, if I have more info. Maybe you find some time to dig into this, too - would be great!

**Comment by AdrienWac** [comment]
Hi @rowild , i have the same issue. Do you find solution to fix it ?

**Comment by rowild** [comment]
Hi, @AdrienWac ! No, I do not have a proper technical solution for that. It seems to be a very complicated thing to (hot reloading when working on partials) and is not restricted to webpack. Vie, e.g., has the same problems, and it seems rollup, too (even though I need to experiment more). Now, with parcel 2 released, I will check, how that package manager behaves.

For the moment, all I do is to keep the "top level" file (the one that includes partials) open, and whenever I make changes to a partial, I also make a quick change to that "top level" file, too (just simply adding an empty line or taking way one). That initiate a complete reload of the page and grasps the changes in the partial(s), too.
I did it so often that it is already in my muscle memory, and it just so happened that I am ok with that workflow nowadays and don't worry too much.
