### ISSUE TITLE
webpack 5 support?

### ISSUE THREAD

**Issue by rowild** [testerum/ejs-compiled-loader-webpack4-nodeps#3]
Is there any chance you could release a version that supports webpack v5? 
Would be so awesome!

**Comment by cvmocanu** [comment]
Hi @rowild .
I'm not using this package anymore, and unfortunately I don't have time now to look into supporting webpack v5.

**Comment by rowild** [comment]
That's a pity! May I ask what you use now for templating (esp with nested templates) with webpack?

You ext was - for me at least - the only one that worked with ejs files. and hot-reloading nested ejs-files is still a problem nowadays... I wonder what other people use (aside from React, Vue, etc, which in my case are not usable, because the final project will not use any of those framework)

**Comment by cvmocanu** [comment]
Since it's a long time ago since I last used it, I spent a few minutes trying to remember where I use it.

If I remember correctly, I'm not using it anymore.
I switched to having an Angular application that renders stuff based on a global variable (i.e. `window.myModel`), and I set that variable in the `index.html` file (the rendering process makes a copy of the application and then replaces a placeholder in `index.html` with the correct model).

**Comment by cvmocanu** [comment]
If you are looking for a simple website generator, I really like [Hexo](https://hexo.io/).

**Comment by rowild** [comment]
Thanks so much for your feedback! So there is no need for ejs in Angular, I assume :-)

No, I do not look for a website generator. I use this webpack templating as an intermediary step between Figma and TYPO3 Fluid integration (Fluid = TYPO3's templating system). That enables me to build the HTML components that can be translated to Fluid, and also to generated the css and JS that I need (without Vue etc).
(This is also the reason why do not use pug, because I actually do not need the rendered HTML, but my own one. Anyway, pug's nested templates also do not initiate a hot reload in webpack...)

Anyway - thanks for reading! :-) Have a great time and stay healthy! I close this issue again!
